### ISSUE TITLE
Fetch zones bug when null

### ISSUE THREAD

**Issue by rsnodgrass** [rsnodgrass/hass-adtpulse#11]
From: jimcj1301 Jim
See https://community.home-assistant.io/t/adt-ha-issue/181253/6

Good Morning, I’ve had this issue with the integration for a while and not sure what the cause it. Just getting around to work on it. I just updated to your latest version but this has been going on for the last 3 or 4 for me. Might have started around 116 of HA. Checks my config.yaml and the login is all correct. Here’s a log snippet… and suggestions on how I can fix this?

```
Logger: homeassistant.setup

Source: custom_components/adtpulse/__init__.py:60

First occurred: 7:43:30 AM (1 occurrences)

Last logged: 7:43:30 AM



Error during setup of component adtpulse

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component

    result = await task

  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/config/custom_components/adtpulse/__init__.py", line 60, in setup

    service = PyADTPulse(username, password)

  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/__init__.py", line 43, in __init__

    self.login()

  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/__init__.py", line 140, in login

    self._update_sites(response.text)

  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/__init__.py", line 78, in _update_sites

    self._initialize_sites(soup)

  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/__init__.py", line 101, in _initialize_sites

    sites.append( ADTPulseSite(self, site_id, site_name, soup) )

  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/site.py", line 43, in __init__

    self._update_alarm_status(summary_html_soup)

  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/site.py", line 142, in _update_alarm_status

    self.fetch_zones()

  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/site.py", line 184, in fetch_zones

    value = devInfoRow.find_next_sibling().get_text().strip()

AttributeError: 'NoneType' object has no attribute 'get_text'
```

**Comment by rsnodgrass** [comment]
Resolved in pyadtpulse
