### ISSUE TITLE
ADT Pulse Custom Integration Fails to Load

### ISSUE THREAD

**Issue by prrandy** [rsnodgrass/hass-adtpulse#23]
All of a sudden I'm getting this error code every time ADT Pluse tried to load on startup of HA. Any help would be appreciated. I'm running HA Core 2022.3.6. Thanks.

``
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/adtpulse/__init__.py:86
Integration: ADT Pulse (documentation, issues)
First occurred: 1:26:51 PM (11 occurrences)
Last logged: 7:32:37 PM

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/adtpulse/__init__.py", line 86, in refresh_adtpulse_data
    adtpulse_service.update()
  File "/usr/local/lib/python3.9/site-packages/pyadtpulse/__init__.py", line 232, in update
    self._update_sites(response.text)
  File "/usr/local/lib/python3.9/site-packages/pyadtpulse/__init__.py", line 88, in _update_sites
    site._update_alarm_status(soup, update_zones=True)
  File "/usr/local/lib/python3.9/site-packages/pyadtpulse/site.py", line 142, in _update_alarm_status
    self.fetch_zones()
  File "/usr/local/lib/python3.9/site-packages/pyadtpulse/site.py", line 151, in fetch_zones
    response2 = self._adt_service.query(ADT_SYSTEM_URI)
  File "/usr/local/lib/python3.9/site-packages/pyadtpulse/__init__.py", line 215, in query
    response = self._session.get(url, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
``

**Comment by rsnodgrass** [comment]
Closing old issues after major update to hass-adtpulse.
