### ISSUE TITLE
ADT setup failed 0.0.4 update

### ISSUE THREAD

**Issue by kcam01** [rsnodgrass/hass-adtpulse#3]
The 0.0.2 version was working before the update to 0.0.4. I rolled back to 0.0.2 and it worked again.

2020-03-01 13:11:45 ERROR (MainThread) [homeassistant.setup] Error during setup of component adtpulse
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/adtpulse/__init__.py", line 63, in setup
    service.set_api_host(host)
AttributeError: 'PyADTPulse' object has no attribute 'set_api_host'
2020-03-01 13:11:45 INFO (MainThread) [homeassistant.setup] Set

**Comment by rsnodgrass** [comment]
For some reason, your installation is using an older pyadtpulse library.  Did you install using HACS or manually copy the integration?

**Comment by rsnodgrass** [comment]
I may have found the issue, let me try one thing.

**Comment by rsnodgrass** [comment]
Try 0.0.5.  This only affected cases where the ADT Pulse service host was manually specified, it was calling the wrong API.

**Comment by kcam01** [comment]
Works! Thank you!
