### ISSUE TITLE
0.0.5 update causing error

### ISSUE THREAD

**Issue by robross0606** [rsnodgrass/hass-adtpulse#5]
Just updated from 0.0.2 to 0.0.5 and started getting the following error on restart:

> The following components and platforms could not be set up:
> adtpulse.alarm_control_panel
> Please check your config.

I haven't changed my configuration at all.

**Comment by rsnodgrass** [comment]
Please make sure your only config looks like:

adtpulse:
  username: your@email.com
  password: your_password

**Comment by robross0606** [comment]
Sorry, I wasn't able to get back to this until today.  My config already looks like that.  As I said, it was working fine and then just stopped working without any changes to my configuration when I upgraded to version 0.0.5.  I just upgraded to 0.0.8 and tried again.  Still no love.  I also tested that I could log into ADT Pulse directly and there is no problem.  My normal credentials still work.  All the entities that were on my dashboard now show "ERROR" markers.

**Comment by robross0606** [comment]
What do you mean by "only" config?  I have other configuration options by necessity in my yaml file, but none of the other ones are in the `adtpulse ` section.

**Comment by robross0606** [comment]
I see errors in my hass.log file as well:
```
2020-03-28 15:01:37 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.hacs
2020-03-28 15:01:40 WARNING (SyncWorker_1) [pyadtpulse.site] Failed to load any zones from ADT Pulse service
2020-03-28 15:01:40 INFO (MainThread) [homeassistant.setup] Setup of domain adtpulse took 5.0 seconds.
2020-03-28 15:01:40 INFO (SyncWorker_1) [homeassistant.loader] Loaded alarm_control_panel from homeassistant.components.alarm_control_panel
2020-03-28 15:01:40 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.adtpulse
2020-03-28 15:01:40 INFO (MainThread) [homeassistant.setup] Setting up alarm_control_panel
2020-03-28 15:01:40 INFO (MainThread) [homeassistant.setup] Setup of domain alarm_control_panel took 0.0 seconds.
2020-03-28 15:01:40 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform adtpulse.alarm_control_panel: Platform not found (No module named 'homeassistant.components.alarm_control_panel.const').
2020-03-28 15:01:40 WARNING (SyncWorker_4) [pyadtpulse.site] Failed to load any zones from ADT Pulse service
2020-03-28 15:01:40 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up platform adtpulse
Traceback (most recent call last):
  File "c:\users\media\homeassistant\lib\site-packages\homeassistant\helpers\entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "C:\Program Files\Python\3\lib\asyncio\tasks.py", line 483, in wait_for
    return fut.result()
  File "C:\Program Files\Python\3\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\media\AppData\Roaming\.homeassistant\custom_components\adtpulse\binary_sensor.py", line 46, in setup_platform
    for zone in site.zones:
TypeError: 'NoneType' object is not iterable
2020-03-28 15:01:46 WARNING (SyncWorker_6) [pyadtpulse.site] Failed to load any zones from ADT Pulse service
2020-03-28 15:01:52 INFO (MainThread) [hacs.factory] Task processing of 2 tasks completed in 6 seconds
2020-03-28 15:01:52 WARNING (SyncWorker_8) [pyadtpulse.site] Failed to load any zones from ADT Pulse service
```

**Comment by robross0606** [comment]
I am also now getting this notification in the UI on restart:
> The following components and platforms could not be set up:
> adtpulse.alarm_control_panel
> Please check your config.

**Comment by robross0606** [comment]
I tried completely uninstalling the adtpulse Integration, ensuring the code was no longer installed, and then reinstalled from scratch.  The log file looks slightly different but still erroring:
```
2020-03-28 15:06:17 INFO (SyncWorker_4) [homeassistant.loader] Loaded alarm_control_panel from homeassistant.components.alarm_control_panel
C:\Users\media\AppData\Roaming\.homeassistant\custom_components\adtpulse\binary_sensor.py:87: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self._device_class is 'door':
2020-03-28 15:06:17 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.adtpulse
2020-03-28 15:06:17 INFO (MainThread) [homeassistant.setup] Setting up alarm_control_panel
2020-03-28 15:06:17 INFO (MainThread) [homeassistant.setup] Setup of domain alarm_control_panel took 0.0 seconds.
2020-03-28 15:06:17 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform adtpulse.alarm_control_panel: Platform not found (No module named 'homeassistant.components.alarm_control_panel.const').
2020-03-28 15:06:17 WARNING (SyncWorker_6) [pyadtpulse.site] Failed to load any zones from ADT Pulse service
2020-03-28 15:06:17 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up platform adtpulse
Traceback (most recent call last):
  File "c:\users\media\homeassistant\lib\site-packages\homeassistant\helpers\entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "C:\Program Files\Python\3\lib\asyncio\tasks.py", line 483, in wait_for
    return fut.result()
  File "C:\Program Files\Python\3\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\media\AppData\Roaming\.homeassistant\custom_components\adtpulse\binary_sensor.py", line 46, in setup_platform
    for zone in site.zones:
TypeError: 'NoneType' object is not iterable
2020-03-28 15:06:21 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 9.05s
```

**Comment by robross0606** [comment]
For additional information, `pip` is showing that version 0.1.3 of pyadtpulse is installed.

**Comment by robross0606** [comment]
Can we please re-open this issue?  It isn't resolved in the slightest.

**Comment by robross0606** [comment]
I have sites and sensors.  I can log directly into ADT Pulse either through the mobile app or web site and see everything.  Obviously, for security reasons, I can't post any proof here.  This also worked absolutely fine up until I upgraded to 0.0.5 and beyond.

**Comment by rsnodgrass** [comment]
Thanks.  I updated again to provide more error logging under this situation, no need to enable debug logging anymore.

Thus if anyone else runs across it, hopefully this will help diagnosis.

**Comment by robross0606** [comment]
Whatever you did in the latest release fixed the problem without me doing anything else at all.  No errors in the log and all my sensors magically came back.

**Comment by rsnodgrass** [comment]
I suspect you may have a second site configured in ADT Pulse (either you or
they did).  There should be an ERROR in the logs.  I'd be curious as to
what it says.

**Comment by robross0606** [comment]
I the hass.log file?  Not seeing any errors at all.
```
2020-04-03 15:48:43 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.adtpulse
2020-04-03 15:48:43 INFO (SyncWorker_5) [custom_components.adtpulse.binary_sensor] Created ADT Pulse 'window' sensor 'Basement Window'
2020-04-03 15:48:43 INFO (SyncWorker_5) [custom_components.adtpulse.binary_sensor] Created ADT Pulse 'window' sensor 'Basement Window (6)'
2020-04-03 15:48:43 INFO (SyncWorker_5) [custom_components.adtpulse.binary_sensor] Created ADT Pulse 'door' sensor 'Front Door'
2020-04-03 15:48:43 INFO (MainThread) [homeassistant.setup] Setting up alarm_control_panel
2020-04-03 15:48:43 INFO (SyncWorker_5) [custom_components.adtpulse.binary_sensor] Created ADT Pulse 'door' sensor 'Garage Door'
2020-04-03 15:48:43 INFO (MainThread) [homeassistant.setup] Setup of domain alarm_control_panel took 0.0 seconds.
2020-04-03 15:48:43 INFO (SyncWorker_5) [custom_components.adtpulse.binary_sensor] Created ADT Pulse 'door' sensor 'Kitchen Door'
2020-04-03 15:48:43 INFO (SyncWorker_5) [custom_components.adtpulse.binary_sensor] Created ADT Pulse 'motion' sensor 'Kitchen Motion Motion'
2020-04-03 15:48:43 INFO (SyncWorker_5) [custom_components.adtpulse.binary_sensor] Created ADT Pulse 'motion' sensor 'Living Room Motion Detector'
2020-04-03 15:48:43 INFO (SyncWorker_5) [custom_components.adtpulse.binary_sensor] Created ADT Pulse 'door' sensor 'Side Door'
2020-04-03 15:48:43 INFO (MainThread) [homeassistant.components.alarm_control_panel] Setting up alarm_control_panel.adtpulse
```

**Comment by robross0606** [comment]
There is no mention of the word "site" in the log file and ADT Pulse web page "site" tab shows a single site.

**Comment by robross0606** [comment]
![image](https://user-images.githubusercontent.com/2965467/78401721-5ef0c300-75c7-11ea-8c8c-d619a32749c5.png)
