### ISSUE TITLE
Update to Core 2024.4 does not import ADT integration

### ISSUE THREAD

**Issue by TGrounds** [rsnodgrass/hass-adtpulse#50]
I just applied the 2024.4 core update and the ADT integration will not load:
![image](https://github.com/rsnodgrass/hass-adtpulse/assets/38465204/c98df7fb-3cb8-41d0-9679-3fb3263a25bb)

Here is the log:
`Logger: homeassistant.setup
Source: setup.py:316
First occurred: 2:19:43 PM (1 occurrences)
Last logged: 2:19:43 PM

Setup failed for custom integration 'adtpulse': Unable to import component: cannot import name 'FlowResult' from 'homeassistant.helpers.config_entry_flow' (/usr/src/homeassistant/homeassistant/helpers/config_entry_flow.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 979, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1037, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/adtpulse/__init__.py", line 22, in <module>
    from homeassistant.helpers.config_entry_flow import FlowResult
ImportError: cannot import name 'FlowResult' from 'homeassistant.helpers.config_entry_flow' (/usr/src/homeassistant/homeassistant/helpers/config_entry_flow.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 316, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 997, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 989, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1037, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/adtpulse/__init__.py", line 22, in <module>
    from homeassistant.helpers.config_entry_flow import FlowResult
ImportError: cannot import name 'FlowResult' from 'homeassistant.helpers.config_entry_flow' (/usr/src/homeassistant/homeassistant/helpers/config_entry_flow.py)
`

**Comment by wxman60** [comment]
I ran into the same issue with the upgrade to m2024.4.

**Comment by skepfish** [comment]
Same, I wonder if it is related to this change https://github.com/home-assistant/core/pull/111932

**Comment by ColinKlayer** [comment]
Same issue with the upgrade to m2024.4

**Comment by skepfish** [comment]
so I'm not sure if this is a long term fix but i made a change in the init.py file to import `FlowResult` from `data_entry_flow` instead of `helpers.config_entry_flow` on line 22. This matched the setting in line 19 of `config_flow.py` and looks to be where the class is defined homeassistant.

Integration is now working again for me for now at least. 

old line: `from homeassistant.helpers.config_entry_flow import FlowResult`
new line: `from homeassistant.data_entry_flow import FlowResult`

**Comment by wxman60** [comment]
skepfish's workaround worked for me as well. Will see how it goes.

**Comment by TGrounds** [comment]
Yes!  Thank you so much for the workaround!

**Comment by norweeg** [comment]
> so I'm not sure if this is a long term fix but i made a change in the init.py file to import `FlowResult` from `data_entry_flow` instead of `helpers.config_entry_flow` on line 22. This matched the setting in line 19 of `config_flow.py` and looks to be where the class is defined homeassistant.
> 
> Integration is now working again for me for now at least.
> 
> old line: `from homeassistant.helpers.config_entry_flow import FlowResult` new line: `from homeassistant.data_entry_flow import FlowResult`

so can you PR that workaround into an actual fix??

**Comment by skepfish** [comment]
> > so I'm not sure if this is a long term fix but i made a change in the init.py file to import `FlowResult` from `data_entry_flow` instead of `helpers.config_entry_flow` on line 22. This matched the setting in line 19 of `config_flow.py` and looks to be where the class is defined homeassistant.
> > Integration is now working again for me for now at least.
> > old line: `from homeassistant.helpers.config_entry_flow import FlowResult` new line: `from homeassistant.data_entry_flow import FlowResult`
> 
> so can you PR that workaround into an actual fix??

PR #51  has been created for review

**Comment by rsnodgrass** [comment]
@skepfish Thank you for PR, it has been merged into main, with version bump to 0.4.5 (but not yet released). If someone can test this and confirm that the main branch is working, we can release this.
