### ISSUE TITLE
Since the new version pyadtpulse 1.1 the below error occurs. 

### ISSUE THREAD

**Issue by drittzz** [rsnodgrass/hass-adtpulse#6]
Since the merge, it broke. I have updated pyadtpulse to 1.1

Logger: homeassistant.setup
Source: custom_components/adtpulse/init.py:58
First occurred: 4:49:34 PM (1 occurrences)
Last logged: 4:49:34 PM

Error during setup of component adtpulse
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
component.setup, hass, processed_config # type: ignore
File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/adtpulse/init.py", line 58, in setup
service = PyADTPulse(username, password)
File "/usr/local/lib/python3.7/site-packages/pyadtpulse/init.py", line 42, in init
self.login()
File "/usr/local/lib/python3.7/site-packages/pyadtpulse/init.py", line 140, in login
self._update_sites(response.text)
File "/usr/local/lib/python3.7/site-packages/pyadtpulse/init.py", line 77, in _update_sites
self._initialize_sites(soup)
File "/usr/local/lib/python3.7/site-packages/pyadtpulse/init.py", line 100, in _initialize_sites
sites.append( ADTPulseSite(self, site_id, site_name, soup) )
File "/usr/local/lib/python3.7/site-packages/pyadtpulse/site.py", line 25, in init
self._update_alarm_status(summary_html_soup)
File "/usr/local/lib/python3.7/site-packages/pyadtpulse/site.py", line 124, in _update_alarm_status
self.fetch_zones()
File "/usr/local/lib/python3.7/site-packages/pyadtpulse/site.py", line 134, in fetch_zones
zones = response.json().get('items')
AttributeError: 'NoneType' object has no attribute 'get'ash-5.0# pip3 install pyadtpulse
Requirement already satisfied: pyadtpulse in /usr/local/lib/python3.7/site-packages (0.1.1)

**Comment by rsnodgrass** [comment]
The latest pyadtpulse will now check for no JSON response from ADT Pulse service and ignore these (which also means no updates for the client).  To debug further, you can enable debug log level for pyadtpulse and see why ADT Pulse service (or some proxy in the middle) is responding without a JSON response.  Thanks.

**Comment by drittzz** [comment]
This seemed to have resolved itself! Thanks for the response and all the work!
