### ISSUE TITLE
Floor water sensor

### ISSUE THREAD

**Issue by damien67** [rsnodgrass/hass-adtpulse#8]
Sorry for the redundancy...I realized that I had posted this in you python repository, not in the HA one. Thought this would be a better place.

Hey Ryan! First of all thank you for this addon, seems to be working well. Since HA dropped the news on depreciating HASS.IO, I decided to see if I could migrate everything I have as addons to other solutions. (news is on hold, but just in case!) Been using Haruny's addon for a while, which works very well too.

Anyways! So I have a floor flood sensor next to a sewer pump in my basement. The addon doesn't know that type of sensor so I get this in my logs:

```
2020-06-01 14:25:38 WARNING (SyncWorker_11) [pyadtpulse.site] Unknown sensor type for Floor Detector, defaulting to doorWindow
2020-06-01 14:25:38 WARNING (SyncWorker_11) [pyadtpulse.site] Unknown sensor type for Floor Detector, defaulting to doorWindow
2020-06-01 14:25:41 WARNING (SyncWorker_18) [pyadtpulse.site] Unknown sensor type for Floor Detector, defaulting to doorWindow
2020-06-01 14:25:47 WARNING (SyncWorker_6) [pyadtpulse.site] Unknown sensor type for Floor Detector, defaulting to doorWindow
```

Problem is that there are a lot of them in my logs. As you can see 14:25, x4. Goes on and on...
I inspected your code, and found in site.py:

```
if "Door" in name or "Window" in name:
                tags = [ 'sensor', 'doorWindow' ] 
            elif "Motion" in name:
                tags = [ 'sensor', 'motion' ] 
            elif "Glass" in name:
                tags = [ 'sensor', 'glass' ] 
            elif "Gas" in name:
                tags = [ 'sensor', 'co' ] 
            elif "Smoke" in name or "Heat" in name:
                tags = [ 'sensor', 'smoke' ]      
            else:
                LOG.warning(f"Unknown sensor type for {name}, defaulting to doorWindow")
                tags = [ 'sensor', 'doorWindow' ]
```

Would it be possible to add another condition such as:

```
            elif "Floor" in name:
                tags = [ 'sensor', 'flood' ]
```
??

I also inspected the ajax responses from ADT, and the floor sensor shows like this (from /ajax/orb.jsp):

`<tr class="p_rowd" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowd')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('XXX=', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: 3/9&nbsp;11:32&nbsp;AM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('XXX=', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/19.0.0-89/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('XXX=', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('XXX=', 672)">Floor Detector</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;11</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('XXX=', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">Okay&nbsp;</td></tr></tr></table></td></tr>`

I looked everywhere trying to find which py file needed to be updated for HA to pick this sensor but could figure this part out! Plus long term it'd be better for this component to be updated for everyone...

Thank you so much in advance. Let me know if you need any other detail from me.

**Comment by rsnodgrass** [comment]
Thanks for the suggestion.  I'm hoping HASS.IO does not get rid of Linux
support, as I run my instance on a Synology NAS.

I've updating pyadtpulse and hass-adtpulse with flood sensors, please
update to the master hass-adtpulse and confirm it is working for you.  I
will then release a new version.

**Comment by damien67** [comment]
Ok...thank you so much for such fast response!
Line 103, missing a ")" in binary_sensor.py.
`LOG.info(f"Determined {self._name} device class {self._device_class} from ADT Pulse service configured tags {tags}"`

I manually added it which took care of the following in HA's logs:

```
2020-06-03 08:31:46 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 139, in component_platform_discovered
    await self.async_setup_platform(platform, {}, info)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 229, in async_setup_platform
    self.hass, self.config, self.domain, platform_type
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 273, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/adtpulse/binary_sensor.py", line 106
    def id(self):
      ^
SyntaxError: invalid syntax
```
After that no more error, and sensor shows as "Dry". 
I'll trip the sensor today to see what happens!

The last pyadtpulse remaining error is:
`2020-06-03 08:37:42 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Entity id already exists - ignoring: alarm_control_panel.adt_my_home. Platform adtpulse does not generate unique IDs`

Seems more of a warning than an error, but I just wanted to point it out.

Thank you!!
