### ISSUE TITLE
Since updating to the latest version 0.1.3 ADTpulse won't start

### ISSUE THREAD

**Issue by MyRandomUsername** [rsnodgrass/hass-adtpulse#9]
I get an error on startup about setup of adtpulse since I updated to the latest version.  Running on Home assistant 0.116.4

2020-10-16 23:35:10 ERROR (MainThread) [homeassistant.setup] Error during setup of component adtpulse
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/adtpulse/__init__.py", line 58, in setup
    service = PyADTPulse(username, password)
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/__init__.py", line 42, in __init__
    self.login()
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/__init__.py", line 140, in login
    self._update_sites(response.text)
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/__init__.py", line 77, in _update_sites
    self._initialize_sites(soup)
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/__init__.py", line 100, in _initialize_sites
    sites.append( ADTPulseSite(self, site_id, site_name, soup) )
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/site.py", line 43, in __init__
    self._update_alarm_status(summary_html_soup)
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/site.py", line 142, in _update_alarm_status
    self.fetch_zones()
  File "/usr/local/lib/python3.8/site-packages/pyadtpulse/site.py", line 172, in fetch_zones
    device_id = result[0]
IndexError: list index out of range

**Comment by rsnodgrass** [comment]
Try the latest release 0.1.4 that pulls in fixes from pyadtpulse from earlier this week
